### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by kartikmehta18** [appwrite/website#1144]
### 💭 Description

in this https://appwrite.io/docs/products/auth/email-password page at Verification section 

.setProject('5df5acd0d48c2')                 // Your project ID
here project id already give I want to correct this from 
.setProject('<PROJECT_ID>')  

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by iamAyushChamoli** [comment]
Hi @kartikmehta18 you've mentioned the issue specifically for  https://appwrite.io/docs/products/auth/email-password page but I've found the same issue on multiple pages. Since this particular issue mentions only this page, I've updated it, just let me know if you would like me to do the same throughout the code base where the same bug happens.

**Comment by stnguyen90** [comment]
@kartikmehta18, sorry, what exactly is the problem?

**Comment by iamAyushChamoli** [comment]
@stnguyen90 He apparently wants to replace the existing Project ID in setProject() method in Appwrite docs with setProject('<PROJECT_ID>')
