### ISSUE TITLE
🚀 Feature: Default Scrollbar doesn't match with the theme of the website

### ISSUE THREAD

**Issue by Swpn0neel** [appwrite/website#327]
### 🔖 Feature description

I want to implement a custom scrollbar that will match with the pink-black theme of the site and will look classy, modern and simplistic just like the rest of the site.

### 🎤 Pitch

This will improve the user experience by smoothening the design consistency throughout the website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Swpn0neel** [comment]
I want to work on this issue, please kindly assign me @TorstenDittmann @wess @eldadfux !!

**Comment by Haimantika** [comment]
Hi @Swpn0neel thanks for raising this issue. We have had a similar one open in the past, but we decided not to go forward with it, since the scrollbar is a browser element that is hard to maintain consistency across different browsers. Plus, styling it is not really something that we see as beneficial for our "design consistency" as it is not an element we want to draw a lot of attention to.

**Comment by Swpn0neel** [comment]
Yes that's true, I understand. Sorry for bothering, you can close the issue then!!
